// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  blog_grid: dynamic(() => import("./BlogGrid")),
  blog_preview: dynamic(() => import("./BlogPreview")),
  body: dynamic(() => import("./Body")),
  call_to_action: dynamic(() => import("./CallToAction")),
  content_grid: dynamic(() => import("./ContentGrid")),
  get_in_touch_block: dynamic(() => import("./GetInTouchBlock")),
  hero: dynamic(() => import("./Hero")),
  highlight: dynamic(() => import("./Highlight")),
  map: dynamic(() => import("./Map")),
  post: dynamic(() => import("./Post")),
  services_preview: dynamic(() => import("./ServicesPreview")),
  testimonials: dynamic(() => import("./Testimonials")),
  video_banner: dynamic(() => import("./VideoBanner")),
};
